model:
  name: moleculestm
  scibert_path: ./checkpoints/moleculestm/scibert
  MoleculeSTM_model_dir: ./checkpoints/moleculestm/demo_checkpoints_SMILES
  language_edit_model_dir: ./checkpoints/moleculestm/demo_checkpoints_SMILES
  vocab_path: ./checkpoints/moleculestm/megamolbart/bart_vocab.txt
  MegaMolBART_generation_model_dir: ./checkpoints/moleculestm/megamolbart/checkpoints
  MoleculeSTM_molecule_type: SMILES
  SSL_emb_dim: 256
  smiles_max_length: 512
  text_max_length: 512
  fusion_n_layer: 4
  fusion_n_head: 4
  batch_size_train: 64
  batch_size_eval: 64
  device: cuda:0
  predict:
    num_beams: 1
    max_length: 512

dataset:
  batch_size_train: 64
  batch_size_eval: 64

train:
  max_epochs: 2
  batch_size: 64
  ckpt_freq: 1

evaluation:
  batch_size: 64